### ISSUE TITLE
how to generate zhe model insightface.pd ?

### ISSUE THREAD

**Issue by WJSAI** [AIInAi/tf-insightface#5]
@AIInAi
hi, thank you for your share. Could you tall me how to generate zhe model insightface.pd ? 
Thank you very much.

**Comment by smartwell** [comment]
yes，i also want to know how to generate the model, you konw now ?

**Comment by smartwell** [comment]
> @AIInAi
> hi, thank you for your share. Could you tall me how to generate zhe model insightface.pd ?
> Thank you very much.
yes，i also want to know how to generate the model, you konw now ?

**Comment by KleinYuan** [comment]
Maybe you shall look at this: https://github.com/deepinsight/insightface#train

This repo is purely still doing a serving without training.

**Comment by Vincent630** [comment]
> Maybe you shall look at this: https://github.com/deepinsight/insightface#train
> 
> This repo is purely still doing a serving without training.

hi,i got this issus when i run the demo.py ,is that because of the camera problem ??? i will appricate it if you can help me .thank you so much
[Camera Server] Camera is initializing ...
VIDEOIO ERROR: V4L: can't open camera by index 0
Traceback (most recent call last):
File "apps/demo.py", line 68, in 
demo.run()
File "/home/wenguang.wang/下载/tf-insightface/models/camera_server.py", line 40, in run
self.processs(frame)
File "apps/demo.py", line 30, in processs
self.face_tracker.process(frame)
File "/home/wenguang.wang/下载/tf-insightface/models/face_track_server.py", line 40, in process
self.cam_h, self.cam_w, _ = frame.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by smartwell** [comment]
> > Maybe you shall look at this: https://github.com/deepinsight/insightface#train
> > This repo is purely still doing a serving without training.
> 
> hi,i got this issus when i run the demo.py ,is that because of the camera problem ??? i will appricate it if you can help me .thank you so much
> [Camera Server] Camera is initializing ...
> VIDEOIO ERROR: V4L: can't open camera by index 0
> Traceback (most recent call last):
> File "apps/demo.py", line 68, in
> demo.run()
> File "/home/wenguang.wang/下载/tf-insightface/models/camera_server.py", line 40, in run
> self.processs(frame)
> File "apps/demo.py", line 30, in processs
> self.face_tracker.process(frame)
> File "/home/wenguang.wang/下载/tf-insightface/models/face_track_server.py", line 40, in process
> self.cam_h, self.cam_w, _ = frame.shape
> AttributeError: 'NoneType' object has no attribute 'shape'
将index 改为-1 试试，linux 有时候会有这个问题，0 默认是usb 摄像机
