### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Vincent630** [AIInAi/tf-insightface#9]
hi,i got this issus when i run the demo.py ,is that because of the camera problem ??? i  will appricate it if you can help me .thank you so much 
[Camera Server] Camera is initializing ...
VIDEOIO ERROR: V4L: can't open camera by index 0
Traceback (most recent call last):
  File "apps/demo.py", line 68, in <module>
    demo.run()
  File "/home/wenguang.wang/下载/tf-insightface/models/camera_server.py", line 40, in run
    self.processs(frame)
  File "apps/demo.py", line 30, in processs
    self.face_tracker.process(frame)
  File "/home/wenguang.wang/下载/tf-insightface/models/face_track_server.py", line 40, in process
    self.cam_h, self.cam_w, _ = frame.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by mengyaogong** [comment]
Did you connect the camera?
